# SPDX-License-Identifier: MIT
version: 2

updates:
- package-ecosystem: docker
  directory: build/package
  schedule:
    interval: monthly
  labels:
  - dependabot
  rebase-strategy: auto

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  labels:
  - dependabot
  rebase-strategy: auto
  groups:
    actions-minor:
      patterns:
      - '*'
      update-types:
      - minor
      - patch

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: monthly
  allow:
  - dependency-type: direct
  labels:
  - dependabot
  rebase-strategy: auto
  groups:
    gomod-minor:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
