# SPDX-License-Identifier: MIT
version: 2

updates:
- package-ecosystem: 'docker'
  directory: 'build/package'
  schedule:
    interval: 'monthly'
  assignees:
  - 'ffurrer2'
  labels:
  - 'dependabot'
  open-pull-requests-limit: 999
  rebase-strategy: 'auto'

- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'monthly'
  assignees:
  - 'ffurrer2'
  labels:
  - 'dependabot'
  open-pull-requests-limit: 999
  rebase-strategy: 'auto'
  groups:
    go-dependencies:
      patterns:
      - '*'
      update-types:
      - 'minor'
      - 'patch'

- package-ecosystem: 'gomod'
  directory: '/'
  schedule:
    interval: 'monthly'
  allow:
  - dependency-type: 'direct'
  assignees:
  - 'ffurrer2'
  labels:
  - 'dependabot'
  open-pull-requests-limit: 999
  rebase-strategy: 'auto'
  groups:
    go-dependencies:
      patterns:
      - '*'
      update-types:
      - 'minor'
      - 'patch'
