# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  lint:
    desc: Lint Go code
    cmds:
    - golangci-lint run --out-format colored-line-number --issues-exit-code 0 --tests --print-resources-usage --config .github/linters/.golangci.yml
    silent: true

  lint:fix:
    desc: Lint Go code and fix errors
    cmds:
    - golangci-lint run --out-format colored-line-number --issues-exit-code 0 --tests --print-resources-usage --config .github/linters/.golangci.yml --fix
    silent: true

  linters:
    desc: List golangci-lint linters
    cmds:
    - golangci-lint linters --config .github/linters/.golangci.yml
    silent: true
