# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  check:
    desc: Check GoReleaser configuration
    cmds:
    - goreleaser check --config build/package/.goreleaser.yaml
    silent: true

  build:
    desc: Build with GoReleaser
    env:
      SNAPSHOT_VERSION: '{{.BUILD_VERSION}}'
    cmds:
    - goreleaser build --config build/package/.goreleaser.yaml --clean --snapshot
    silent: true

  snapshot:
    desc: Create snapshot release with GoReleaser
    vars:
      IMAGE_BASE_NAME_DISTROLESS: {sh: 'sed -n "s/^FROM \(.*\)/\1/p" build/package/Dockerfile'}
      IMAGE_BASE_DIGEST_DISTROLESS: {sh: 'docker pull {{.IMAGE_BASE_NAME_DISTROLESS}} | sed -n "s/^Digest: \(.*\)$/\1/p"'}
      IMAGE_BASE_NAME_ALPINE: {sh: 'sed -n "s/^FROM \(.*\)/\1/p" build/package/Dockerfile.alpine'}
      IMAGE_BASE_DIGEST_ALPINE: {sh: 'docker pull {{.IMAGE_BASE_NAME_ALPINE}} | sed -n "s/^Digest: \(.*\)$/\1/p"'}
    env:
      SNAPSHOT_VERSION: '{{.BUILD_VERSION}}'
      IMAGE_BASE_NAME_DISTROLESS: '{{.IMAGE_BASE_NAME_DISTROLESS}}'
      IMAGE_BASE_DIGEST_DISTROLESS: '{{.IMAGE_BASE_DIGEST_DISTROLESS}}'
      IMAGE_BASE_NAME_ALPINE: '{{.IMAGE_BASE_NAME_ALPINE}}'
      IMAGE_BASE_DIGEST_ALPINE: '{{.IMAGE_BASE_DIGEST_ALPINE}}'
    cmds:
    - echo '{{.BUILD_VERSION}}'
    - goreleaser release --config build/package/.goreleaser.yaml --clean --snapshot
    silent: true

  release-dry-run:
    desc: Create release with GoReleaser without publishing artifacts
    vars:
      IMAGE_BASE_NAME_DISTROLESS: {sh: 'sed -n "s/^FROM \(.*\)/\1/p" build/package/Dockerfile'}
      IMAGE_BASE_DIGEST_DISTROLESS: {sh: 'docker pull {{.IMAGE_BASE_NAME_DISTROLESS}} | sed -n "s/^Digest: \(.*\)$/\1/p"'}
      IMAGE_BASE_NAME_ALPINE: {sh: 'sed -n "s/^FROM \(.*\)/\1/p" build/package/Dockerfile.alpine'}
      IMAGE_BASE_DIGEST_ALPINE: {sh: 'docker pull {{.IMAGE_BASE_NAME_ALPINE}} | sed -n "s/^Digest: \(.*\)$/\1/p"'}
    env:
      IMAGE_BASE_NAME_DISTROLESS: '{{.IMAGE_BASE_NAME_DISTROLESS}}'
      IMAGE_BASE_DIGEST_DISTROLESS: '{{.IMAGE_BASE_DIGEST_DISTROLESS}}'
      IMAGE_BASE_NAME_ALPINE: '{{.IMAGE_BASE_NAME_ALPINE}}'
      IMAGE_BASE_DIGEST_ALPINE: '{{.IMAGE_BASE_DIGEST_ALPINE}}'
    cmds:
    - goreleaser release --config build/package/.goreleaser.yaml --clean --skip-publish
    silent: true
