# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

vars:
  GO_BUILD_ENV: CGO_ENABLED=0
  LDFLAGS: >-
    -X github.com/ffurrer2/semver/v2/internal/pkg/app.version={{.BUILD_VERSION}}
    -s -w -extldflags "-static"

tasks:
  clean:
    desc: Delete Go build artifacts
    cmds:
    - rm -rf artifacts/
    silent: true

  download:
    desc: Download required dependencies
    cmds:
    - go mod download -x
    silent: true

  verify:
    desc: Verify downloaded dependencies
    cmds:
    - go mod verify
    silent: true

  build:
    desc: Build {{.PROJECT_NAME}}
    cmds:
    - task: download
    - mkdir -p artifacts/bin
    - |-
      {{.GO_BUILD_ENV}} go build -o artifacts/bin -v -ldflags='{{.LDFLAGS}}' -mod=mod -trimpath ./cmd/semver
    silent: true

  test:
    desc: Run tests
    cmds:
    - task: download
    - mkdir -p artifacts/coverage-results
    - go test -race -covermode atomic -v -coverprofile artifacts/coverage-results/coverage.out ./...
    - go tool cover -html artifacts/coverage-results/coverage.out -o artifacts/coverage-results/coverage.html
    silent: true

  install:
    desc: Install {{.PROJECT_NAME}} into $GOPATH/bin
    cmds:
    - task: download
    - |-
      {{.GO_BUILD_ENV}} go install -ldflags='{{.LDFLAGS}}' -v ./cmd/semver
    silent: true

  tidy:
    desc: Tidy go.mod
    cmds:
    - go mod tidy -v
    silent: true

  vendor:
    desc: Create vendor directory
    cmds:
    - go mod vendor -v
    silent: true

  check-dependency-updates:
    desc: Check dependency updates
    cmds:
    - |-
      go list -mod=mod -u -f {{`'{{if (and (not (or .Main .Indirect)) .Update)}}{{.Path}}: {{.Version}} -> {{.Update.Version}}{{end}}'`}} -m all
    silent: true

  # https://github.com/oligot/go-mod-upgrade
  # go install github.com/oligot/go-mod-upgrade@latest
  go-mod-upgrade:
    desc: Run go-mod-upgrade
    cmds:
    - go-mod-upgrade
    - task: tidy
    silent: true

  gofmt:
    desc: Format code with gofmt
    cmds:
    - go fmt ./...
    silent: true

  # https://github.com/mvdan/gofumpt
  # go install mvdan.cc/gofumpt@latest
  gofumpt:
    desc: Format code with gofumpt
    cmds:
    - gofumpt -l -w -extra .
    silent: true

  # https://cs.opensource.google/go/x/tools
  # go install golang.org/x/tools/cmd/goimports@latest
  goimports:
    desc: Optimize imports with goimports
    vars:
      MODULE_PATH: {sh: go list -m}
    cmds:
    - goimports -w -local {{.MODULE_PATH}} .
    silent: true
