# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  list:
    desc: List dependencies
    cmds:
    - licensed list
    silent: true

  status:
    desc: Check licensed status
    cmds:
    - licensed status
    silent: true

  cache:
    desc: Update licensed cache
    cmds:
    - licensed cache --force
    - |
      sed -i.bak 's/license: other/license: bsd-3-clause/g' .licenses/go/golang.org/x/exp/constraints.dep.yml
    - find ./.licenses/go -type f -name '*.bak' -delete
    silent: true

  notices:
    desc: Generate NOTICE file
    cmds:
    - licensed notices
    silent: true
