# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  lint:
    desc: Lint Markdown files
    cmds:
    - docker run -it --rm --volume "$(pwd):/work" --workdir /work docker.io/tmknom/markdownlint:latest --config .github/linters/.markdown-lint.yml .
    silent: true
