# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  lint:
    desc: Lint Markdown files
    vars:
      ADDITIONAL_ARGS: '{{.ADDITIONAL_ARGS}}'
    cmds:
    - docker run -it --rm --volume "$(pwd):/work" --workdir /work ghcr.io/tmknom/dockerfiles/markdownlint:latest --config .github/linters/.markdown-lint.yml --dot --ignore node_modules/ {{.ADDITIONAL_ARGS}} .
    silent: true
