# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  container-structure-test:
    desc: Run container structure tests
    cmds:
    - container-structure-test test --image ghcr.io/ffurrer2/semver:latest --config test/semver_container_test.yml

  grype:
    desc: Run Grype scan
    cmds:
    - grype ghcr.io/ffurrer2/semver:latest
