# https://taskfile.dev
version: '3'

tasks:
  scan:
    desc: Run shiftleft scan
    vars:
      OUT_DIR: '{{default "artifacts/shiftleft-reports" .OUT_DIR }}'
    cmds:
    - docker run --rm --env DISABLE_TELEMETRY=true --volume "$(pwd):/app" shiftleft/scan:latest scan --build --type credscan,go,yaml,bash,depscan --out_dir '{{.OUT_DIR}}'
    silent: true
