# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  image:scan:
    desc: Run Trivy image scanner
    preconditions:
    - sh: '{{if empty .IMAGE_NAME}}false{{end}}'
      msg: 'error: variable "IMAGE_NAME" is required (e.g. task trivy:image IMAGE_NAME=docker.io/library/ubuntu:latest)'
    cmds:
    - trivy image --format table {{.IMAGE_NAME}}
    silent: true

  filesystem:scan:
    desc: Run Trivy filesystem scanner
    cmds:
    - trivy filesystem --scanners vuln,misconfig,secret,license --skip-dirs .idea --dependency-tree --format table .
    silent: true
