# SPDX-License-Identifier: MIT
# https://taskfile.dev
version: '3'

tasks:
  lint:
    desc: Lint YAML files
    cmds:
    - docker run -it --rm --volume "$(pwd):/work" --workdir /work docker.io/cytopia/yamllint:latest --config-file .github/linters/.yaml-lint.yml --format auto --strict .
    silent: true
