# SPDX-License-Identifier: MIT
linters-settings:
  lll:
    line-length: 160

linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - deadcode
  - decorder
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exhaustive
  - exportloopref
  - forbidigo
  - forcetypeassert
  - funlen
  - gci
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - grouper
  - importas
  - ineffassign
  - ireturn
  - lll
  - maintidx
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosnakecase
  - nosprintfhostport
  - paralleltest
  - prealloc
  - predeclared
  - promlinter
  - revive
  - staticcheck
  - stylecheck
  - tagliatelle
  - tenv
  - testpackage
  - thelper
  - tparallel
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - varcheck
  - whitespace
  - wrapcheck

  # Don't enable:
  # - cyclop
  # - dupl
  # - exhaustivestruct
  # - exhaustruct
  # - gochecknoglobals
  # - gochecknoinits
  # - godot
  # - goerr113
  # - nlreturn
  # - varnamelen
  # - wsl

  # Disabled because of generics:
  # - contextcheck
  # - rowserrcheck
  # - sqlclosecheck
  # - structcheck
  # - wastedassign

run:
  timeout: 5m
