# SPDX-License-Identifier: MIT
linters-settings:
  lll:
    line-length: 160
  depguard:
    rules:
      main:
        allow:
        - $gostd
        - github.com/ffurrer2
        - github.com/go-task/slim-sprig/v3
        - github.com/onsi
        - github.com/samber/lo
        - github.com/spf13/cobra
        deny:
        - pkg: github.com/pkg/errors
          desc: Should be replaced by standard lib errors package
        - pkg: golang.org/x/net/context
          desc: Should be replaced by standard lib context package

linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - containedctx
  - contextcheck
  - copyloopvar
  - decorder
  - depguard
  - dogsled
  - dupword
  - durationcheck
  - err113
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - fatcontext
  - forbidigo
  - forcetypeassert
  - funlen
  - ginkgolinter
  - gocheckcompilerdirectives
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - intrange
  - ireturn
  - lll
  - loggercheck
  - maintidx
  - makezero
  - mirror
  - misspell
  - mnd
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - paralleltest
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tagliatelle
  - tenv
  - testableexamples
  - testifylint
  - testpackage
  - thelper
  - tparallel
  - unconvert
  - unparam
  - unused
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  - wrapcheck
  - zerologlint

  # Don't enable:
  # - cyclop
  # - dupl
  # - exhaustruct
  # - gci
  # - gochecknoglobals
  # - gochecknoinits
  # - godot
  # - nlreturn
  # - revive
  # - varnamelen
  # - wsl

run:
  timeout: 5m
