# SPDX-License-Identifier: MIT
name: 'Dependency Review'

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  dependency-review:
    name: dependency-review
    uses: ffurrer2/shared-workflows/.github/workflows/dependency-review.yml@main
