# SPDX-License-Identifier: MIT
name: hadolint

on:
  push:
    branches:
    - main
    - feature/**
    paths:
    - '**/Dockerfile*'
    - '.github/workflows/hadolint.yml'
  pull_request:
    branches:
    - main
    paths:
    - '**/Dockerfile*'
    - '.github/workflows/hadolint.yml'

jobs:
  hadolint:
    name: hadolint
    uses: ffurrer2/shared-workflows/.github/workflows/hadolint.yml@main
    with:
      args: 'hadolint --format tty build/package/Dockerfile'
