# SPDX-License-Identifier: MIT
name: hadolint

on:
  push:
    branches:
    - main
    - feature/**
    - dependabot/**
    paths:
    - '**/Dockerfile*'
    - '.github/workflows/hadolint.yml'

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: hadolint
      uses: docker://hadolint/hadolint:latest
      with:
        args: 'hadolint --format tty build/package/Dockerfile build/package/Dockerfile.alpine'
