# SPDX-License-Identifier: MIT
name: Lint

on:
  push:
    branches:
    - master
    - feature/**
    paths:
    - '**.go'
    - '**.md'
    - '**.sh'
    - '**.ya?ml'
    - '**/Dockerfile*'

env:
  GOLANGCI_LINT_VERSION: 1.27

jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Shellcheck
      uses: docker://koalaman/shellcheck:latest
      with:
        entrypoint: /bin/shellcheck
        args: '--check-sourced --color=auto --format=tty --enable=all --shell=bash --severity=style --source-path=scripts scripts/branch.sh scripts/version.sh'

  yamllint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: yamllint
      uses: docker://ffurrer/yamllint:latest
      with:
        args: '--format auto --strict .'

  hadolint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: hadolint
      uses: docker://hadolint/hadolint:latest
      with:
        args: 'hadolint --format tty build/docker/Dockerfile build/docker/Dockerfile.alpine'

  golangci-lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v${{ env.GOLANGCI_LINT_VERSION }}
        args: '--tests --issues-exit-code 0'

  markdownlint:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: markdownlint
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
        config_file: .markdownlint.yml
        ignore_files: SECURITY.md
