# SPDX-License-Identifier: MIT
name: ORT

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
    - '.gitignore'

jobs:
  ort:
    name: ORT
    runs-on: ubuntu-24.04
    steps:
    - name: Use HTTPS instead of SSH for Git cloning
      run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run GitHub Action for ORT
      uses: oss-review-toolkit/ort-ci-github-action@1805edcf1f4f55f35ae6e4d2d9795ccfb29b6021 # v1.1.0
