# SPDX-License-Identifier: MIT
name: shiftleft

on:
  push:
    branches:
    - main
    - feature/**
    paths-ignore:
    - '**.md'
    - '.gitignore'
  pull_request:
    branches:
    - main

env:
  GO_VERSION: 1.18

jobs:
  shiftleft:
    name: ShiftLeft
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Perform ShiftLeft scan
      uses: ShiftLeftSecurity/scan-action@v1.3.0
      env:
        WORKSPACE: ''
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
        DISABLE_TELEMETRY: true
        SKIP_BOT_TRIGGERS: false
      with:
        type: credscan,go,yaml,bash,depscan
        output: artifacts/shiftleft-reports

    - name: Upload ShiftLeft reports
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: artifacts/shiftleft-reports
