# SPDX-License-Identifier: MIT
name: shiftleft

on:
  push:
    branches:
    - main
    - feature/**
    paths-ignore:
    - '**.md'
    - '.gitignore'

env:
  GO_VERSION: 1.15
  TASK_VERSION: 3.0.0

jobs:
  shiftleft:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Set up task
      run: |
        sudo bash -c 'curl -fsSL https://taskfile.dev/install.sh | bash -s -- -b /usr/local/bin v${{ env.TASK_VERSION }}'
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Perform ShiftLeft scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ''
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
        DISABLE_TELEMETRY: true
      with:
        type: credscan,go,yaml,bash,depscan
        output: artifacts/shiftleft-reports
    - name: Upload ShiftLeft reports
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: artifacts/shiftleft-reports
